### ISSUE TITLE
`go get` fails -- undefined: authy.NewAuthyApi

### ISSUE THREAD

**Issue by pirogoeth** [dcu/onetouch-ssh#1]
I'm trying to build this, but alas, the build fails:

```
# github.com/dcu/onetouch-ssh
.go/src/github.com/dcu/onetouch-ssh/user.go:93: undefined: authy.NewAuthyApi
```

I tried downloading your `go-authy` library first and rebuilding, but still nothing:

```
root@gamma:~# go get github.com/dcu/go-authy
root@gamma:~# go get github.com/dcu/onetouch-ssh
# github.com/dcu/onetouch-ssh
.go/src/github.com/dcu/onetouch-ssh/user.go:93: undefined: authy.NewAuthyApi
```

Could this be some idiocy with my environment?

**Comment by dcu** [comment]
no it actually was my fault.
I just refactored a lot of code to simplify everything. It should be fine now.
Can you try again and let me know how it goes?

**Comment by pirogoeth** [comment]
It works! Awesome, thanks! I'm really looking forward to playing with this :)

**Comment by dcu** [comment]
nice! if you have feature requests please add them as issues
