### ISSUE TITLE
OpenBSD: invalid argument

### ISSUE THREAD

**Issue by kolargol** [dcu/onetouch-ssh#21]
I got issue after successful auth:
```
onetouch-ssh shell XXXXX  
Sending approval request to your device... [sent]
You've been logged in successfully.
invalid argument
```

on the app i see "Login on to: exit 1" so i suspect it cannot get hostname on BSD? And as a result exit code 1, users are unable to login.

**Comment by kolargol** [comment]
issue appear to be in ssh/verification.go:
```
 hostname := utils.RunCommand("hostname", "-f") // Use -f to get FQDN
```
there is no -f switch on OpenBSD, in general i think -f is not needed, but that's my opinion ;)

**Comment by dcu** [comment]
sounds good, do you want to send a patch for it?

**Comment by kolargol** [comment]
simple solution is jut to remove "-f" but maybe some folks use fqdn, maybe there is better way to detect if we deal with bsd systems and then get hostname other way around. I will try to see that later today.

**Comment by kolargol** [comment]
Use golang function to get hostname, I have not tested this patch but it get proper hostname in my case https://github.com/kolargol/onetouch-ssh/commit/c4540cae4540d2b52126678e1db05319fc8955bc

**Comment by kolargol** [comment]
the patch is bit invalid, sorry i will fix it later :)

**Comment by kolargol** [comment]
@dcu sorry, finally get that right, here is tested patch: https://github.com/kolargol/onetouch-ssh/commit/7cdc7b6c24e1de8202bdcb98d16350178e118f28 it works now.

**Comment by dcu** [comment]
awesome, can you send a pull request?

**Comment by kolargol** [comment]
actually this resolves only one issue related with in-proper hostname ("exit 1"). 
Invalid argument is still there, I have narrowed problem and it looks like it's around run_shell.go line 77 - looks like syscall.ForkExec() have invalid parameters. Any idea?

**Comment by dcu** [comment]
what version of go are you using?

**Comment by kolargol** [comment]
that is 1.8

**Comment by dcu** [comment]
ok do you have any special shell config in `~/.authy-onetouch/config.yml` ?

**Comment by kolargol** [comment]
no, just:
```
api_key: xxxxxx
shell: /bin/sh
shell_args: []
```

**Comment by dcu** [comment]
@kolargol please sync with master and then run:

`go test github.com/dcu/onetouch-ssh/utils/ -run TestDetachCommand`

**Comment by kolargol** [comment]
```
go test github.com/dcu/onetouch-ssh/utils/ -run TestDetachCommand
# github.com/dcu/onetouch-ssh/utils
github.com/dcu/onetouch-ssh/utils/geoip_test.go:4:2: cannot find package "github.com/stretchr/testify/assert" in any of:
        /usr/local/go/src/github.com/stretchr/testify/assert (from $GOROOT)
        /root/go/src/github.com/stretchr/testify/assert (from $GOPATH)
FAIL    github.com/dcu/onetouch-ssh/utils [setup failed]
```

**Comment by dcu** [comment]
sync again and try `glide install` first

**Comment by kolargol** [comment]
this time:
```
 go test github.com/dcu/onetouch-ssh/utils/ -run TestDetachCommand
ok      github.com/dcu/onetouch-ssh/utils       0.009s
```

**Comment by kolargol** [comment]
and more details:
```
Sending approval request to your device... [sent]
You've been logged in successfully.
invalid argument
panic: invalid argument

goroutine 1 [running]:
github.com/dcu/onetouch-ssh/utils.RunShellFromPath(0xc420398460, 0x7)
        /root/go/src/github.com/dcu/onetouch-ssh/utils/run_shell.go:44 +0x13a
github.com/dcu/onetouch-ssh/ssh.runShell()
        /root/go/src/github.com/dcu/onetouch-ssh/ssh/verification.go:93 +0xcc
github.com/dcu/onetouch-ssh/ssh.(*Verification).Run(0xc4200ab500, 0x5, 0xc4200ab500)
        /root/go/src/github.com/dcu/onetouch-ssh/ssh/verification.go:65 +0x2cb
github.com/dcu/onetouch-ssh/cmd.glob..func7(0x9cbce0, 0xc420017f20, 0x1, 0x1)
        /root/go/src/github.com/dcu/onetouch-ssh/cmd/shell.go:47 +0x59
github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra.(*Command).execute(0x9cbce0, 0xc420017ee0, 0x1, 0x1, 0x9cbce0, 0xc420017ee0)
        /root/go/src/github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra/command.go:654 +0x299
github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x9cbaa0, 0xc420054058, 0x0, 0x7384d9)
        /root/go/src/github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra/command.go:729 +0x339
github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra.(*Command).Execute(0x9cbaa0, 0x9cbaa0, 0xc420047f50)
        /root/go/src/github.com/dcu/onetouch-ssh/vendor/github.com/spf13/cobra/command.go:688 +0x2b
github.com/dcu/onetouch-ssh/cmd.Execute()
        /root/go/src/github.com/dcu/onetouch-ssh/cmd/root.go:42 +0x31
main.main()
        /root/go/src/github.com/dcu/onetouch-ssh/main.go:26 +0x20
```

**Comment by dcu** [comment]
that's really strange, looks like executing `/bin/sh` is not working, does that file exist for you? try changing the value of it in your config file to see what happens

**Comment by kolargol** [comment]
i just tried with /bin/ksh, and bash - same result

**Comment by dcu** [comment]
I pushed a new change to print more information about the error, can you try that?

**Comment by kolargol** [comment]
here it goes:
```
Failed to run `/bin/sh []`: invalid argument
```

**Comment by dcu** [comment]
ok please sync and try again 🤞

**Comment by kolargol** [comment]
latest commit fixes issue! thanks, i have just tested.

**Comment by dcu** [comment]
awesome, thanks for taking the time to test
