### ISSUE TITLE
Error: Public Key was not found

### ISSUE THREAD

**Issue by iuri-gg** [dcu/onetouch-ssh#25]
I set up onetouch-ssh on centos 7 vm. When trying to log in, I see request was sent and I get notification on my cell. When I click approve button on my cell, I get Error message on the phone saying: `There was an error processing the request: Public Key was not found`. Is there some setting I am missing on Authy side? Using code works correctly if I wait long enough...

**Comment by dcu** [comment]
hi @ocha are you getting that in the server or in the app?

**Comment by iuri-gg** [comment]
hi @dcu. Im getting it in the iOS App

**Comment by dcu** [comment]
what's your authy id? I think you can get that from settings

**Comment by iuri-gg** [comment]
36637. I havent found any reference to public key anywhere in the app...

**Comment by iuri-gg** [comment]
I was able to approve request from a Desktop App I just downloaded. However iOS still doesnt work. I assume there is something wrong with iOS App

**Comment by dcu** [comment]
@ocha can you try again please? with the iOS app

**Comment by iuri-gg** [comment]
same error on iOS, works with Desktop

**Comment by iuri-gg** [comment]
is there some private key generated for iOS app when installing? I've had that app installed for more than a year...

**Comment by dcu** [comment]
yeah, the key is generated locally, I marked your device for regeneration but it's not syncing, can you check if it has internet? also, please try closing the app completely and opening it again

**Comment by iuri-gg** [comment]
It has internet and can receive requests. I also quit it in iOS and started it again but still got same error. I have TouchID Enable for what it's worth.

**Comment by dcu** [comment]
yeah apparently it's an iOS bug, we will try to prioritize for next sprint. In the meantime please try reinstalling

**Comment by iuri-gg** [comment]
Thank you. Makes sense
