### ISSUE TITLE
Add command to remove a user

### ISSUE THREAD

**Issue by dcu** [dcu/onetouch-ssh#5]

**Comment by jtenniswood** [comment]
You can remove users via the authy dashboard, its not the same but works.

**Comment by pirogoeth** [comment]
@jtenniswood It's not quite just removing the user from the Authy dashboard - I believe this issue is more focused toward being able to easily remove a key from the authorized_keys that onetouch-ssh generates.

**Comment by dcu** [comment]
I just pushed a command to do this
